#pragma once

#define CRY_COLOR_CODE_BLACK   0
#define CRY_COLOR_CODE_WHITE   1
#define CRY_COLOR_CODE_BLUE    2
#define CRY_COLOR_CODE_GREEN   3
#define CRY_COLOR_CODE_RED     4
#define CRY_COLOR_CODE_CYAN    5
#define CRY_COLOR_CODE_YELLOW  6
#define CRY_COLOR_CODE_MAGENTA 7
#define CRY_COLOR_CODE_ORANGE  8
#define CRY_COLOR_CODE_GRAY    9

#define CRY_COLOR_CODE_BLACK_STRING   "$0"
#define CRY_COLOR_CODE_WHITE_STRING   "$1"
#define CRY_COLOR_CODE_BLUE_STRING    "$2"
#define CRY_COLOR_CODE_GREEN_STRING   "$3"
#define CRY_COLOR_CODE_RED_STRING     "$4"
#define CRY_COLOR_CODE_CYAN_STRING    "$5"
#define CRY_COLOR_CODE_YELLOW_STRING  "$6"
#define CRY_COLOR_CODE_MAGENTA_STRING "$7"
#define CRY_COLOR_CODE_ORANGE_STRING  "$8"
#define CRY_COLOR_CODE_GRAY_STRING    "$9"
