################################################################################
# Developer workflow running on pushes to the master branch and pull requests
################################################################################

name: Dev

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_x86:
    uses: ./.github/workflows/build.yml
    with:
      arch: x86
      type: Release

  build_x64:
    uses: ./.github/workflows/build.yml
    with:
      arch: x64
      type: Release
